import {chromium} from 'playwright';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir,writeFile} from 'node:fs/promises';
const server=spawn(process.execPath,['shared-racer/scripts/serve.mjs'],{env:{...process.env,APP_BASE:'/James-Game-Center/'},stdio:'inherit'}),root='http://127.0.0.1:4173/James-Game-Center/';let browser,page;const errors=[],checks=[];const ok=s=>{checks.push(s);console.log('PASS',s);};await mkdir('dist/qa',{recursive:true});
async function overflow(){return page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.right>innerWidth+1||r.left< -1);}).map(e=>({tag:e.tagName,id:e.id,cls:typeof e.className==='string'?e.className:'svg',rect:{x:e.getBoundingClientRect().x,width:e.getBoundingClientRect().width}})).slice(0,25)}));}
try{
 for(let i=0;i<50;i++){try{if((await fetch(root)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1440,height:1100}});page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(root);await page.waitForFunction(()=>window.__hubReady);await page.waitForTimeout(300);assert.equal(await page.title(),'James Game Center');assert.ok((await page.locator('#game-play').getAttribute('href')).startsWith('/James-Hulk-Racer/'));assert.equal(await page.locator('.explore-section .world-card').count(),3);ok('Hub links to the racer and all three worlds');await page.screenshot({path:'dist/qa/desktop.png',fullPage:true});
 await page.locator('.profile-btn').click();await page.locator('#nickname').fill('James Hero');await page.locator('#nickname-form button').click();await page.locator('#profile-dialog [data-close]').click();await page.reload();await page.waitForFunction(()=>window.__hubReady);assert.equal(await page.locator('.profile-btn [data-name]').textContent(),'James Hero');ok('Nickname persists after refresh');
 await page.evaluate(()=>{const p=JSON.parse(localStorage.getItem('james-center:profile:v1'));p.runs=3;p.gems=120;p.medals=[7,1,0];p.lastLevel=2;localStorage.setItem('james-center:profile:v1',JSON.stringify(p));});await page.reload();await page.waitForFunction(()=>window.__hubReady);assert.equal(await page.locator('.mini-stats [data-gems]').textContent(),'120');assert.equal(await page.locator('#hero-play').getAttribute('href'),'/James-Hulk-Racer/emerald/');assert.equal(await page.locator('.world-card.park').getAttribute('href'),'/James-Hulk-Racer/emerald/');assert.equal(await page.locator('.world-card.cavern').getAttribute('href'),'/James-Hulk-Racer/?level=1');ok('Racer-format progress appears in the hub');
 await page.locator('.trophy-banner [data-dialog="trophies"]').click();assert.ok(await page.locator('#trophy-grid .earned').count()>0);await page.locator('#trophies-dialog [data-close]').click();ok('Trophy room reflects earned achievements');
 await page.locator('#music-toggle').click();await page.waitForFunction(()=>document.getElementById('music-toggle').getAttribute('aria-pressed')==='true');await page.locator('#music-toggle').click();await page.waitForFunction(()=>document.getElementById('music-toggle').getAttribute('aria-pressed')==='false');ok('Music starts and stops after a gesture');
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'dist/qa/phone.png',fullPage:true});const bounds=await overflow();console.log('MOBILE BOUNDS',JSON.stringify(bounds));assert.ok(bounds.documentWidth<=bounds.width+1);ok('390px phone layout stays within viewport');assert.deepEqual(errors,[]);ok('No uncaught browser errors');
 const report={result:'PASS',checks,errors};await writeFile('dist/qa/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){const bounds=page?await overflow().catch(()=>null):null;console.error('LAYOUT DIAGNOSTIC',JSON.stringify(bounds));await page?.screenshot({path:'dist/qa/failure.png',fullPage:true}).catch(()=>{});await writeFile('dist/qa/report.json',JSON.stringify({result:'FAIL',checks,errors,bounds,error:e.stack},null,2));console.error(e);process.exitCode=1;}finally{await browser?.close();server.kill();}
