import '../shared-racer/src/shared/style.css';
import './style.css';
import {profile,settings,medalCount,trophies} from '../shared-racer/src/shared/profile.js';
import {header,icon,installDialogs,toast,RACER} from '../shared-racer/src/shared/ui.js';
import {AudioEngine} from '../shared-racer/src/game/audio.js';
import {installCommunity} from '../shared-racer/src/shared/community.js';
import {GAMES,WORLDS} from './games.js';
const app=document.querySelector('#app'),game=GAMES[0],audio=new AudioEngine(settings);let music=false,installEvent;
app.innerHTML=`${header()}<main><section class="hero"><div class="hero-orbit orbit-one" aria-hidden="true"></div><div class="hero-orbit orbit-two" aria-hidden="true"></div><div class="hero-copy"><span class="eyebrow"><i class="live-dot"></i> WELCOME TO JAMES GAME CENTER</span><h1>Little superheroes.<br><em>Big adventures.</em></h1><p>A place to be brave. A place to have fun.<br>A whole world of Jamesy is waiting for you.</p><div class="hero-actions"><a id="hero-play" class="btn" href="${game.url}">${icon('play')} Let’s play ${icon('right')}</a><button class="btn secondary" data-dialog="profile">${icon('user')} My hero card</button></div><div class="hero-details"><span>${icon('shield')} Made for little heroes</span><span>${icon('gem')} Big powers to discover</span></div></div><div class="hero-portrait"><div class="portrait-ring"></div><div class="portrait-image"><img src="${RACER}emerald/media/portrait.png" alt="Jamesy, the orange-haired superhero in his green and purple suit" onerror="this.style.display='none'"><div class="portrait-fallback" aria-hidden="true"><span>J</span></div></div><div class="portrait-label"><small>YOUR FIRST SUPERHERO</small><strong>Jamesy The Hulk</strong><span>Strong. Brave. Ready to race.</span></div><span class="floating-gem gem-a" aria-hidden="true">${icon('gem')}</span><span class="floating-gem gem-b" aria-hidden="true">${icon('star')}</span><span class="floating-gem gem-c" aria-hidden="true">${icon('bolt')}</span></div></section>
<section class="welcome-bar" aria-label="Your progress"><div><span class="welcome-avatar">J</span><p>Hey, <strong data-name></strong>.<span>Your next adventure starts here.</span></p></div><div class="mini-stats"><div><strong data-runs></strong><span>Adventures</span></div><div><strong data-gems></strong><span>Treasures</span></div><button data-dialog="trophies"><strong data-medals></strong><span>World medals ${icon('right')}</span></button></div></section>
<section class="library-section" aria-labelledby="games-title"><div class="section-heading"><div><span class="eyebrow">THE ADVENTURE LIBRARY</span><h2 id="games-title">Choose your superpower.</h2></div><span class="library-count">01 GAME · MORE TO COME</span></div><div class="library-grid"><article class="featured-game"><div class="featured-art"><img src="${game.art}" alt="The illustrated Emerald Park adventure" onerror="this.style.display='none'"><span class="pill">${icon('bolt')} FIRST ADVENTURE</span><span class="art-caption">EMERALD PARK · NEW ART</span></div><div class="featured-body"><div class="game-heading"><div class="app-icon"><img src="${game.icon}" alt="" onerror="this.style.display='none'"><span aria-hidden="true">J</span></div><div><small>${game.genre}</small><h3>${game.title}</h3><p>${game.subtitle}</p></div></div><p class="game-description">Race a curved half-pipe with animated gems, swaying trees, and rocks that crumble when you Smash. Try the new Emerald Park practice adventure.</p><div class="game-tags"><span>Curved half-pipe</span><span>Animated sprites</span><span>Touch + keyboard</span></div><div class="game-actions"><a class="btn" id="game-play" href="${game.url}">${icon('play')} Play now</a><button class="text-btn" data-dialog="help">How to play ${icon('right')}</button></div></div></article><aside class="next-chapter"><div class="mystery-emblem" aria-hidden="true">${icon('shield')}<span>?</span></div><span class="eyebrow">THE NEXT CHAPTER</span><h3>Every hero has<br>another adventure.</h3><p>More James superheroes will find their home right here.</p><span class="coming-soon">FUTURE ADVENTURES</span><div class="chapter-line" aria-hidden="true"><i></i><i></i><i></i></div></aside></div></section>
<section class="explore-section" aria-labelledby="worlds-title"><div class="section-heading"><div><span class="eyebrow">INSIDE HULK RACER</span><h2 id="worlds-title">Three worlds to explore.</h2></div><span>New illustrated Emerald Park adventure</span></div><div class="world-grid">${WORLDS.map((w,i)=>`<a class="world-card ${w.id}" href="${w.url||`${RACER}?level=${i}`}"><div class="world-art"><img src="${w.id==='park'?game.art:`${RACER}assets/${w.id}.webp`}" alt="" loading="lazy" onerror="this.style.visibility='hidden'"><span class="world-number">0${i+1}</span><span class="world-medals" data-world-medals="${i}"></span></div><div class="world-info"><strong>${w.name}</strong><span>${w.treasures}</span><small>EXPLORE WORLD ${i+1}</small></div></a>`).join('')}</div></section>
<section class="trophy-banner"><div class="trophy-emblem">${icon('trophy')}</div><div><span class="eyebrow">CELEBRATE EVERY LITTLE WIN</span><h2>Your hero story is growing.</h2><p id="trophy-progress"></p></div><button class="btn secondary" data-dialog="trophies">Open trophy room ${icon('right')}</button></section>
<section class="home-tips"><div><span>${icon('home')}</span><div><h3>A little adventure, one tap away.</h3><p>Add James Game Center to your home screen so your next adventure is always close.</p></div></div><button class="text-btn" id="install-button">Add to home screen ${icon('right')}</button></section></main><footer class="hub-footer"><div><span class="footer-wordmark">JAMES <small>GAME CENTER</small></span><span>Little heroes. Unlimited imagination.</span></div><button class="text-btn" id="music-toggle" aria-pressed="false">${icon('volume')} Music off</button><strong>Created by Sean</strong></footer>`;
const dialogs=installDialogs(()=>{if(music&&settings.music===0)audio.stop();else if(music)audio.start(0);});installCommunity();
function refresh(){for(const el of document.querySelectorAll('[data-world-medals]')){const m=profile.medals[Number(el.dataset.worldMedals)];el.innerHTML=[1,2,4].map(n=>icon('star',m&n?'earned':'')).join('');}document.querySelector('#trophy-progress').textContent=`${trophies().filter(t=>t.earned).length} of 6 trophies earned · ${medalCount()} of 9 world medals collected`;for(const id of['hero-play','game-play'])document.getElementById(id).href=game.url;}
window.addEventListener('james-profile',refresh);refresh();
const musicButton=document.getElementById('music-toggle');
musicButton.addEventListener('click',async()=>{await audio.unlock();music=!music;if(music)audio.start(0);else audio.stop();musicButton.setAttribute('aria-pressed',String(music));musicButton.innerHTML=icon('volume')+(music?' Music on':' Music off');if(music&&settings.music===0)toast('Music volume is at zero. Raise it in Settings.');});
document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.stop();else if(music)audio.start(0);});window.addEventListener('pagehide',()=>audio.stop());
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});document.getElementById('install-button').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;}else dialogs.open('help');};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));window.__hubReady=true;
